// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otksdfphbgneusgjvjzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a3NkZnBoYmduZXVzZ2p2anpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMDg3NDEsImV4cCI6MjA4NTc4NDc0MX0.jC3DWtfInA7hl6Zv4RKuvtqsCoPpUCVN8CW66LaagUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});